spring.application.name=GenAI

#Mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/genaidb?useSSL=false&serverTimezone=UTC
spring.datasource.username=genai
spring.datasource.password=genai

# UTF-8 encode for greek characters
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.tomcat.uri-encoding=UTF-8

# Spring boot securit
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.springframework.security=DEBUG
